ci: add `pre-commit` hook to protect `.env` info

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,13 +1,17 @@
+
 SENSITIVE_PATTERNS='(AWS_SECRET_ACCESS_KEY|API_KEY|PRIVATE_KEY|PASSWORD|TOKEN|SECRET|POSTGRES_PASSWORD|DATABASE_URL)'
 
-if [ -z "$FILES_TO_CHECK" ]; then
-    exit 0
-fi
-
-if git diff --cached $FILES_TO_CHECK | grep -E "$SENSITIVE_PATTERNS"; then
-    echo "🚨 ERROR: A sensitive key was detected in the files you are trying to commit!"
-    echo "🛑 Commit has been blocked. Remove the credentials before proceeding."
-    exit 1
-fi
+git diff --cached --name-only | grep -E '\.env$|\.json$|\.yml$|\.yaml$|\.js$|\.ts$|\.py$|\.sh$' | while read file; do
+    if [[ "$file" == ".husky/pre-commit" ]]; then
+        continue
+    fi
+    
+    echo "🔍 Verificando credenciais no arquivo: $file"
+    if git diff --cached "$file" | grep -E "$SENSITIVE_PATTERNS"; then
+        echo "🚨 ERROR: A sensitive key was detected in the file: $file"
+        echo "🛑 Commit has been blocked. Remove the credentials before proceeding."
+        exit 1
+    fi
+done
 
 exit 0
